import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service – Wes Sonnenreich",
  description: "Terms of service for Wes Sonnenreich's website and What Would Wes Do plugin.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <Link href="/" className="inline-flex items-center text-red-600 hover:text-red-800 mb-8">
          <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Home
        </Link>

        <header className="mb-12">
          <h1 className="text-4xl font-bold mb-4 text-gray-900 dark:text-white">Terms of Service</h1>
          <p className="text-gray-500 dark:text-gray-400">Last updated: July 2026</p>
        </header>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-8 text-gray-700 dark:text-gray-300">

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Acceptance</h2>
            <p>
              By accessing <strong>sonnenreich.com</strong> or using the <strong>What Would Wes Do</strong> ChatGPT plugin,
              you agree to these terms. If you do not agree, do not use the site or plugin.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">What Would Wes Do Plugin</h2>
            <p>
              The What Would Wes Do plugin provides advisory content generated by AI based on Wes Sonnenreich&apos;s
              published work and frameworks. The advice is informational only.
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>Advice is not a substitute for professional legal, financial, medical, or psychological counsel.</li>
              <li>Responses are generated by AI and may contain errors or omissions.</li>
              <li>Do not submit confidential, sensitive, or personal identifying information.</li>
              <li>The plugin is provided as-is with no warranty of fitness for any particular purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Use the site or plugin for unlawful purposes.</li>
              <li>Attempt to reverse-engineer, scrape, or overload the service.</li>
              <li>Submit content that is abusive, harassing, or violates third-party rights.</li>
              <li>Use the plugin to generate advice intended to harm others.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Intellectual Property</h2>
            <p>
              All content on sonnenreich.com — including presentations, articles, and frameworks — is the property of
              Wes Sonnenreich unless otherwise noted. You may not reproduce or distribute it without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Wes Sonnenreich is not liable for any indirect, incidental, or
              consequential damages arising from use of this site or the plugin. Total liability is limited to USD $0
              as no fees are charged for access.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Changes</h2>
            <p>
              These terms may be updated at any time. Continued use of the site or plugin after changes constitutes
              acceptance of the updated terms. The &quot;last updated&quot; date at the top of this page reflects the most
              recent revision.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Governing Law</h2>
            <p>These terms are governed by the laws of New South Wales, Australia.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">Contact</h2>
            <p>
              Questions about these terms?{" "}
              <Link href="/contact" className="text-red-600 hover:text-red-800 underline">
                Get in touch
              </Link>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
