'use client';

import React, { useState } from 'react';
import AskProcessor from './ask-processor';
import QAReviewInterface from './qa-review-interface';

interface ParsedQuestion {
  id: string;
  number: string;
  question: string;
  fullText: string;
}

interface AIAnswer {
  questionId: string;
  answer: string;
  confidence: number;
  sources: Array<{
    documentId: string;
    filename: string;
    section: string;
    relevance: number;
  }>;
  status: 'pending' | 'processing' | 'completed' | 'flagged' | 'approved';
  flagReason?: string;
}

interface AskProps {
  organizationId: string;
}

export default function Ask({ organizationId }: AskProps) {
  const [questions, setQuestions] = useState<ParsedQuestion[]>([]);
  const [answers, setAnswers] = useState<AIAnswer[]>([]);
  const [currentStep, setCurrentStep] = useState<'input' | 'review'>('input');

  const handleQAGenerated = (generatedQuestions: ParsedQuestion[], generatedAnswers: AIAnswer[]) => {
    setQuestions(generatedQuestions);
    setAnswers(generatedAnswers);
    setCurrentStep('review');
  };

  const handleAnswerUpdate = (questionId: string, updatedAnswer: AIAnswer) => {
    setAnswers(prev => prev.map(answer => 
      answer.questionId === questionId ? updatedAnswer : answer
    ));
  };

  const handleExportMarkdown = () => {
    const markdown = generateMarkdown(questions, answers);
    downloadMarkdown(markdown);
  };

  const generateMarkdown = (questions: ParsedQuestion[], answers: AIAnswer[]): string => {
    const now = new Date();
    // timestamp variable is available but using now directly for formatting
    
    let markdown = `# Security Questionnaire Responses\n\n`;
    markdown += `**Generated:** ${now.toLocaleDateString()} ${now.toLocaleTimeString()}\n`;
    markdown += `**Organization:** ${organizationId}\n`;
    markdown += `**AI Processing:** PolySec with knowledgebase integration\n\n`;
    
    // Summary stats
    const approvedCount = answers.filter(a => a.status === 'approved').length;
    const flaggedCount = answers.filter(a => a.status === 'flagged').length;
    const completedCount = answers.filter(a => a.status === 'completed').length;
    const totalSources = answers.reduce((sum, a) => sum + a.sources.length, 0);
    
    markdown += `## Summary\n\n`;
    markdown += `- **Total Questions:** ${questions.length}\n`;
    markdown += `- **Approved Answers:** ${approvedCount}\n`;
    markdown += `- **High Confidence:** ${completedCount}\n`;
    markdown += `- **Flagged for Review:** ${flaggedCount}\n`;
    markdown += `- **Total References:** ${totalSources}\n\n`;
    
    markdown += `---\n\n`;

    // Questions and answers
    questions.forEach((question) => {
      const answer = answers.find(a => a.questionId === question.id);
      if (!answer) return;

      markdown += `## Q${question.number}: ${question.question}\n\n`;
      
      // Status badge
      let statusEmoji = '';
      switch (answer.status) {
        case 'approved': statusEmoji = '✅ APPROVED'; break;
        case 'completed': statusEmoji = '✅ HIGH CONFIDENCE'; break;
        case 'flagged': statusEmoji = '⚠️ FLAGGED'; break;
        default: statusEmoji = '⏳ PENDING'; break;
      }
      
      markdown += `**Status:** ${statusEmoji} | **Confidence:** ${Math.round(answer.confidence * 100)}%\n\n`;
      
      // Answer
      markdown += `### Answer\n\n`;
      markdown += `${answer.answer}\n\n`;
      
      // Sources
      if (answer.sources.length > 0) {
        markdown += `### References\n\n`;
        answer.sources.forEach((source, idx) => {
          markdown += `${idx + 1}. **${source.filename}** (${Math.round(source.relevance * 100)}% relevance)\n`;
          markdown += `   - ${source.section}\n`;
          markdown += `   - Document ID: \`${source.documentId}\`\n\n`;
        });
      }
      
      // Flag reason if any
      if (answer.flagReason) {
        markdown += `### Review Notes\n\n`;
        markdown += `**Flag Reason:** ${answer.flagReason}\n\n`;
      }
      
      markdown += `---\n\n`;
    });

    // Footer
    markdown += `## Generated by PolySec AI\n\n`;
    markdown += `This document was generated using PolySec's AI-powered security questionnaire processor. `;
    markdown += `Answers are based on semantic analysis of uploaded policy documents using vector similarity search `;
    markdown += `and AI language models.\n\n`;
    markdown += `**Important:** Please review all flagged answers and verify references before submission. `;
    markdown += `This tool provides assistance but human oversight is required for accuracy.\n`;

    return markdown;
  };

  const downloadMarkdown = (content: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    
    const timestamp = new Date().toISOString().split('T')[0];
    link.download = `security-questionnaire-${timestamp}.md`;
    link.href = url;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleStartOver = () => {
    setQuestions([]);
    setAnswers([]);
    setCurrentStep('input');
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Navigation */}
      <div className="bg-white border border-gray-200 px-6 py-4 rounded-lg">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-4">
            
            {/* Step Indicator */}
            <div className="flex items-center gap-2">
              <div className={`px-3 py-1 rounded-full text-sm font-medium ${
                currentStep === 'input' 
                  ? 'bg-blue-100 text-blue-800' 
                  : 'bg-green-100 text-green-800'
              }`}>
                {currentStep === 'input' ? '1. Process Questions' : '✓ Questions Processed'}
              </div>
              
              <div className="text-gray-300">→</div>
              
              <div className={`px-3 py-1 rounded-full text-sm font-medium ${
                currentStep === 'review' 
                  ? 'bg-blue-100 text-blue-800' 
                  : 'bg-gray-100 text-gray-600'
              }`}>
                2. Review & Export
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-2">
            {currentStep === 'review' && (
              <button
                onClick={handleStartOver}
                className="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 flex items-center gap-2"
              >
                <span>🔄</span>
                Start Over
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto">
        {currentStep === 'input' ? (
          <AskProcessor 
            organizationId={organizationId}
            onQAGenerated={handleQAGenerated}
          />
        ) : (
          <QAReviewInterface
            questions={questions}
            answers={answers}
            organizationId={organizationId}
            onAnswerUpdate={handleAnswerUpdate}
            onExportMarkdown={handleExportMarkdown}
          />
        )}
      </div>

      {/* Info Footer */}
      <div className="bg-white border-t border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-sm text-gray-600">
            <div>
              <h3 className="font-medium text-gray-900 mb-2">🤖 AI-Powered Analysis</h3>
              <p>Uses real semantic search and vector similarity to find relevant policy sections and generate accurate answers.</p>
            </div>
            <div>
              <h3 className="font-medium text-gray-900 mb-2">✅ Human Verification</h3>
              <p>Review, approve, or flag answers for regeneration. Export only when you&apos;re satisfied with the quality.</p>
            </div>
            <div>
              <h3 className="font-medium text-gray-900 mb-2">📄 Source Attribution</h3>
              <p>Every answer includes references to specific document sections with relevance scores for transparency.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 